// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lyfebloc/liquiditypool/ticker.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type TickInfo struct {
	PoolId         uint64                                      `protobuf:"varint,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	TickIndex      int64                                       `protobuf:"varint,2,opt,name=tick_index,json=tickIndex,proto3" json:"tick_index,omitempty"`
	LiquidityGross cosmossdk_io_math.LegacyDec                 `protobuf:"bytes,3,opt,name=liquidity_gross,json=liquidityGross,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"liquidity_gross" yaml:"liquidity_gross"`
	LiquidityNet   cosmossdk_io_math.LegacyDec                 `protobuf:"bytes,4,opt,name=liquidity_net,json=liquidityNet,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"liquidity_net" yaml:"liquidity_net"`
	FeeGrowth      github_com_cosmos_cosmos_sdk_types.DecCoins `protobuf:"bytes,5,rep,name=fee_growth,json=feeGrowth,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.DecCoins" json:"fee_growth"`
}

func (m *TickInfo) Reset()         { *m = TickInfo{} }
func (m *TickInfo) String() string { return proto.CompactTextString(m) }
func (*TickInfo) ProtoMessage()    {}
func (*TickInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_29121fe4c8f3f9b0, []int{0}
}
func (m *TickInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TickInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TickInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TickInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TickInfo.Merge(m, src)
}
func (m *TickInfo) XXX_Size() int {
	return m.Size()
}
func (m *TickInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TickInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TickInfo proto.InternalMessageInfo

func (m *TickInfo) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *TickInfo) GetTickIndex() int64 {
	if m != nil {
		return m.TickIndex
	}
	return 0
}

func (m *TickInfo) GetFeeGrowth() github_com_cosmos_cosmos_sdk_types.DecCoins {
	if m != nil {
		return m.FeeGrowth
	}
	return nil
}

func init() {
	proto.RegisterType((*TickInfo)(nil), "lyfebloc.liquiditypool.TickInfo")
}

func init() {
	proto.RegisterFile("lyfebloc/liquiditypool/ticker.proto", fileDescriptor_29121fe4c8f3f9b0)
}

var fileDescriptor_29121fe4c8f3f9b0 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xed, 0xa6, 0x14, 0xb2, 0x7c, 0x49, 0x56, 0x55, 0xac, 0x02, 0xb6, 0x65, 0x2e, 0x96,
	0x10, 0xbb, 0x2a, 0x3d, 0x01, 0xe2, 0x12, 0x2a, 0x55, 0x95, 0x10, 0x07, 0xc3, 0x89, 0x4b, 0xb0,
	0xd7, 0x63, 0x67, 0xe5, 0x8f, 0x31, 0xde, 0x2d, 0x8d, 0xdf, 0x82, 0xe7, 0xe0, 0x49, 0x7a, 0xec,
	0x11, 0x71, 0x08, 0x28, 0x79, 0x03, 0x1e, 0x00, 0xa1, 0xb5, 0x13, 0x03, 0x39, 0x71, 0xda, 0x9d,
	0xd9, 0xff, 0xfc, 0x7f, 0xa3, 0x99, 0x25, 0x8f, 0x8a, 0x36, 0x85, 0xb8, 0x40, 0xce, 0x0a, 0xf1,
	0xf1, 0x5c, 0x24, 0x42, 0xb5, 0x35, 0x62, 0xc1, 0x94, 0xe0, 0x39, 0x34, 0xb4, 0x6e, 0x50, 0xa1,
	0x75, 0xb0, 0x11, 0xd1, 0x7f, 0x44, 0x87, 0xfb, 0x19, 0x66, 0xd8, 0x49, 0x98, 0xbe, 0xf5, 0xea,
	0x43, 0x87, 0xa3, 0x2c, 0x51, 0xb2, 0x38, 0x92, 0xc0, 0x3e, 0x1d, 0xc5, 0xa0, 0xa2, 0x23, 0xc6,
	0x51, 0x54, 0xfd, 0xbb, 0xff, 0x6b, 0x87, 0xdc, 0x78, 0x27, 0x78, 0x7e, 0x56, 0xa5, 0x68, 0xdd,
	0x23, 0xd7, 0xb5, 0xd5, 0x54, 0x24, 0xb6, 0xe9, 0x99, 0xc1, 0x6e, 0xb8, 0xa7, 0xc3, 0xb3, 0xc4,
	0x7a, 0x48, 0x88, 0xee, 0x61, 0x2a, 0xaa, 0x04, 0xe6, 0xf6, 0x8e, 0x67, 0x06, 0xa3, 0x70, 0xac,
	0xba, 0xb2, 0x04, 0xe6, 0x56, 0x4a, 0xee, 0x0e, 0xbd, 0x4c, 0xb3, 0x06, 0xa5, 0xb4, 0x47, 0x9e,
	0x19, 0x8c, 0x27, 0x2f, 0x2f, 0x17, 0xae, 0xf1, 0x6d, 0xe1, 0xde, 0xef, 0xbb, 0x90, 0x49, 0x4e,
	0x05, 0xb2, 0x32, 0x52, 0x33, 0xfa, 0x1a, 0xb2, 0x88, 0xb7, 0x27, 0xc0, 0x7f, 0x2e, 0xdc, 0x83,
	0x36, 0x2a, 0x8b, 0xe7, 0xfe, 0x96, 0x87, 0x1f, 0xde, 0x19, 0x32, 0xa7, 0x3a, 0x61, 0x7d, 0x20,
	0xb7, 0xff, 0x68, 0x2a, 0x50, 0xf6, 0x6e, 0x47, 0x79, 0xf1, 0x7f, 0x94, 0xfd, 0x6d, 0x4a, 0x05,
	0xca, 0x0f, 0x6f, 0x0d, 0xf1, 0x1b, 0x50, 0x56, 0x4d, 0x48, 0x0a, 0xa0, 0xf9, 0x17, 0x6a, 0x66,
	0x5f, 0xf3, 0x46, 0xc1, 0xcd, 0xa7, 0x0f, 0x68, 0xef, 0x4b, 0xf5, 0x0c, 0xe9, 0x7a, 0x86, 0xf4,
	0x04, 0xf8, 0x2b, 0x14, 0xd5, 0xe4, 0x58, 0xc3, 0xbf, 0x7c, 0x77, 0x1f, 0x67, 0x42, 0xcd, 0xce,
	0x63, 0xca, 0xb1, 0x64, 0xeb, 0x99, 0xf7, 0xc7, 0x13, 0x99, 0xe4, 0x4c, 0xb5, 0x35, 0xc8, 0x4d,
	0x8d, 0x0c, 0xc7, 0x29, 0xc0, 0x69, 0xc7, 0x98, 0xbc, 0xbd, 0x5c, 0x3a, 0xe6, 0xd5, 0xd2, 0x31,
	0x7f, 0x2c, 0x1d, 0xf3, 0xf3, 0xca, 0x31, 0xae, 0x56, 0x8e, 0xf1, 0x75, 0xe5, 0x18, 0xef, 0x9f,
	0xfd, 0xe5, 0xb8, 0xd9, 0x79, 0x05, 0xea, 0x02, 0x9b, 0x7c, 0x88, 0xd9, 0x7c, 0xfb, 0xab, 0x68,
	0x50, 0xbc, 0xd7, 0x2d, 0xf7, 0xf8, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0x0c, 0xce, 0x87,
	0x51, 0x02, 0x00, 0x00,
}

func (m *TickInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TickInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TickInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FeeGrowth) > 0 {
		for iNdEx := len(m.FeeGrowth) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeeGrowth[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTicker(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	{
		size := m.LiquidityNet.Size()
		i -= size
		if _, err := m.LiquidityNet.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTicker(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.LiquidityGross.Size()
		i -= size
		if _, err := m.LiquidityGross.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTicker(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.TickIndex != 0 {
		i = encodeVarintTicker(dAtA, i, uint64(m.TickIndex))
		i--
		dAtA[i] = 0x10
	}
	if m.PoolId != 0 {
		i = encodeVarintTicker(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTicker(dAtA []byte, offset int, v uint64) int {
	offset -= sovTicker(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *TickInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovTicker(uint64(m.PoolId))
	}
	if m.TickIndex != 0 {
		n += 1 + sovTicker(uint64(m.TickIndex))
	}
	l = m.LiquidityGross.Size()
	n += 1 + l + sovTicker(uint64(l))
	l = m.LiquidityNet.Size()
	n += 1 + l + sovTicker(uint64(l))
	if len(m.FeeGrowth) > 0 {
		for _, e := range m.FeeGrowth {
			l = e.Size()
			n += 1 + l + sovTicker(uint64(l))
		}
	}
	return n
}

func sovTicker(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTicker(x uint64) (n int) {
	return sovTicker(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TickInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTicker
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TickInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TickInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TickIndex", wireType)
			}
			m.TickIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TickIndex |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityGross", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTicker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTicker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LiquidityGross.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityNet", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTicker
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTicker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LiquidityNet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeGrowth", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTicker
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTicker
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTicker
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeGrowth = append(m.FeeGrowth, types.DecCoin{})
			if err := m.FeeGrowth[len(m.FeeGrowth)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTicker(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTicker
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTicker(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTicker
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTicker
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTicker
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTicker
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTicker
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTicker
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTicker        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTicker          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTicker = fmt.Errorf("proto: unexpected end of group")
)
