// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lyfebloc/da/metadata.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Metadata struct {
	RecoveredDataHash []byte   `protobuf:"bytes,1,opt,name=recovered_data_hash,json=recoveredDataHash,proto3" json:"recovered_data_hash,omitempty"`
	RecoveredDataSize uint64   `protobuf:"varint,2,opt,name=recovered_data_size,json=recoveredDataSize,proto3" json:"recovered_data_size,omitempty"`
	ShardSize         uint64   `protobuf:"varint,3,opt,name=shard_size,json=shardSize,proto3" json:"shard_size,omitempty"`
	ParityShardCount  uint64   `protobuf:"varint,4,opt,name=parity_shard_count,json=parityShardCount,proto3" json:"parity_shard_count,omitempty"`
	ShardUris         []string `protobuf:"bytes,5,rep,name=shard_uris,json=shardUris,proto3" json:"shard_uris,omitempty"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eab9bc46cf7c7b5, []int{0}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return m.Size()
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetRecoveredDataHash() []byte {
	if m != nil {
		return m.RecoveredDataHash
	}
	return nil
}

func (m *Metadata) GetRecoveredDataSize() uint64 {
	if m != nil {
		return m.RecoveredDataSize
	}
	return 0
}

func (m *Metadata) GetShardSize() uint64 {
	if m != nil {
		return m.ShardSize
	}
	return 0
}

func (m *Metadata) GetParityShardCount() uint64 {
	if m != nil {
		return m.ParityShardCount
	}
	return 0
}

func (m *Metadata) GetShardUris() []string {
	if m != nil {
		return m.ShardUris
	}
	return nil
}

func init() {
	proto.RegisterType((*Metadata)(nil), "lyfebloc.da.Metadata")
}

func init() { proto.RegisterFile("lyfebloc/da/metadata.proto", fileDescriptor_6eab9bc46cf7c7b5) }

var fileDescriptor_6eab9bc46cf7c7b5 = []byte{
	// 290 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xeb, 0xbf, 0xfd, 0x11, 0x35, 0x0c, 0x34, 0x30, 0x84, 0x4a, 0x58, 0x15, 0x53, 0x07,
	0x14, 0x0f, 0xbc, 0x01, 0x30, 0x74, 0x61, 0xa1, 0x62, 0x61, 0x89, 0x6e, 0x12, 0x93, 0x58, 0x34,
	0xb9, 0x91, 0xed, 0x00, 0xe9, 0x53, 0xf0, 0x58, 0x8c, 0x9d, 0x10, 0x23, 0x4a, 0x5e, 0x04, 0xc5,
	0x4e, 0x8b, 0x84, 0x58, 0xa2, 0x9c, 0xf3, 0x7d, 0xba, 0x96, 0x0e, 0x9d, 0xae, 0xea, 0x47, 0x11,
	0xad, 0x30, 0xe6, 0x09, 0xf0, 0x5c, 0x18, 0x48, 0xc0, 0x40, 0x50, 0x2a, 0x34, 0xe8, 0x1d, 0x6c,
	0x59, 0x90, 0xc0, 0x74, 0x02, 0xb9, 0x2c, 0x90, 0xdb, 0xaf, 0xe3, 0xd3, 0xd3, 0x18, 0x75, 0x8e,
	0x3a, 0xb4, 0x89, 0xbb, 0xd0, 0xa3, 0x93, 0x14, 0x53, 0x74, 0x7d, 0xf7, 0xe7, 0xda, 0xf3, 0x0f,
	0x42, 0xf7, 0x6f, 0xfb, 0x37, 0xbc, 0x80, 0x1e, 0x2b, 0x11, 0xe3, 0xb3, 0x50, 0x22, 0x09, 0xbb,
	0x26, 0xcc, 0x40, 0x67, 0x3e, 0x99, 0x91, 0xf9, 0xe1, 0xdd, 0x64, 0x87, 0x6e, 0xc0, 0xc0, 0x02,
	0x74, 0xf6, 0x87, 0xaf, 0xe5, 0x5a, 0xf8, 0xff, 0x66, 0x64, 0x3e, 0xfa, 0xe5, 0x2f, 0xe5, 0x5a,
	0x78, 0x67, 0x94, 0xea, 0x0c, 0x54, 0xe2, 0xb4, 0xa1, 0xd5, 0xc6, 0xb6, 0xb1, 0xf8, 0x82, 0x7a,
	0x25, 0x28, 0x69, 0xea, 0xd0, 0x59, 0x31, 0x56, 0x85, 0xf1, 0x47, 0x56, 0x3b, 0x72, 0x64, 0xd9,
	0x81, 0xeb, 0xae, 0xff, 0x39, 0x56, 0x29, 0xa9, 0xfd, 0xff, 0xb3, 0xe1, 0x7c, 0xdc, 0x1f, 0xbb,
	0x57, 0x52, 0x5f, 0x2d, 0xde, 0x1b, 0x46, 0x36, 0x0d, 0x23, 0x5f, 0x0d, 0x23, 0x6f, 0x2d, 0x1b,
	0x6c, 0x5a, 0x36, 0xf8, 0x6c, 0xd9, 0xe0, 0x21, 0x48, 0xa5, 0xc9, 0xaa, 0x28, 0x88, 0x31, 0xe7,
	0xdb, 0x39, 0x0b, 0x61, 0x5e, 0x50, 0x3d, 0xed, 0x32, 0x7f, 0xed, 0xc6, 0x37, 0x75, 0x29, 0x74,
	0xb4, 0x67, 0x97, 0xba, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xa9, 0x71, 0x87, 0x98, 0x01,
	0x00, 0x00,
}

func (m *Metadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Metadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Metadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ShardUris) > 0 {
		for iNdEx := len(m.ShardUris) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ShardUris[iNdEx])
			copy(dAtA[i:], m.ShardUris[iNdEx])
			i = encodeVarintMetadata(dAtA, i, uint64(len(m.ShardUris[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.ParityShardCount != 0 {
		i = encodeVarintMetadata(dAtA, i, uint64(m.ParityShardCount))
		i--
		dAtA[i] = 0x20
	}
	if m.ShardSize != 0 {
		i = encodeVarintMetadata(dAtA, i, uint64(m.ShardSize))
		i--
		dAtA[i] = 0x18
	}
	if m.RecoveredDataSize != 0 {
		i = encodeVarintMetadata(dAtA, i, uint64(m.RecoveredDataSize))
		i--
		dAtA[i] = 0x10
	}
	if len(m.RecoveredDataHash) > 0 {
		i -= len(m.RecoveredDataHash)
		copy(dAtA[i:], m.RecoveredDataHash)
		i = encodeVarintMetadata(dAtA, i, uint64(len(m.RecoveredDataHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintMetadata(dAtA []byte, offset int, v uint64) int {
	offset -= sovMetadata(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Metadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RecoveredDataHash)
	if l > 0 {
		n += 1 + l + sovMetadata(uint64(l))
	}
	if m.RecoveredDataSize != 0 {
		n += 1 + sovMetadata(uint64(m.RecoveredDataSize))
	}
	if m.ShardSize != 0 {
		n += 1 + sovMetadata(uint64(m.ShardSize))
	}
	if m.ParityShardCount != 0 {
		n += 1 + sovMetadata(uint64(m.ParityShardCount))
	}
	if len(m.ShardUris) > 0 {
		for _, s := range m.ShardUris {
			l = len(s)
			n += 1 + l + sovMetadata(uint64(l))
		}
	}
	return n
}

func sovMetadata(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMetadata(x uint64) (n int) {
	return sovMetadata(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Metadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetadata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Metadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Metadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecoveredDataHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecoveredDataHash = append(m.RecoveredDataHash[:0], dAtA[iNdEx:postIndex]...)
			if m.RecoveredDataHash == nil {
				m.RecoveredDataHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecoveredDataSize", wireType)
			}
			m.RecoveredDataSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RecoveredDataSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardSize", wireType)
			}
			m.ShardSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ShardSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParityShardCount", wireType)
			}
			m.ParityShardCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParityShardCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShardUris", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ShardUris = append(m.ShardUris, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMetadata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMetadata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMetadata(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMetadata
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetadata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMetadata
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMetadata
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMetadata
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMetadata        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMetadata          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMetadata = fmt.Errorf("proto: unexpected end of group")
)
