// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lyfebloc/da/params.proto

package types

import (
	bytes "bytes"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	VoteThreshold       cosmossdk_io_math.LegacyDec              `protobuf:"bytes,1,opt,name=vote_threshold,json=voteThreshold,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"vote_threshold"`
	SlashEpoch          uint64                                   `protobuf:"varint,2,opt,name=slash_epoch,json=slashEpoch,proto3" json:"slash_epoch,omitempty"`
	EpochMaxFault       uint64                                   `protobuf:"varint,3,opt,name=epoch_max_fault,json=epochMaxFault,proto3" json:"epoch_max_fault,omitempty"`
	SlashFraction       cosmossdk_io_math.LegacyDec              `protobuf:"bytes,4,opt,name=slash_fraction,json=slashFraction,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"slash_fraction"`
	ReplicationFactor   cosmossdk_io_math.LegacyDec              `protobuf:"bytes,5,opt,name=replication_factor,json=replicationFactor,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"replication_factor"`
	MinShardCount       uint64                                   `protobuf:"varint,6,opt,name=min_shard_count,json=minShardCount,proto3" json:"min_shard_count,omitempty"`
	MaxShardCount       uint64                                   `protobuf:"varint,7,opt,name=max_shard_count,json=maxShardCount,proto3" json:"max_shard_count,omitempty"`
	MaxShardSize        uint64                                   `protobuf:"varint,8,opt,name=max_shard_size,json=maxShardSize,proto3" json:"max_shard_size,omitempty"`
	ChallengePeriod     time.Duration                            `protobuf:"bytes,9,opt,name=challenge_period,json=challengePeriod,proto3,stdduration" json:"challenge_period"`
	ProofPeriod         time.Duration                            `protobuf:"bytes,10,opt,name=proof_period,json=proofPeriod,proto3,stdduration" json:"proof_period"`
	ChallengeCollateral github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,11,rep,name=challenge_collateral,json=challengeCollateral,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"challenge_collateral"`
	ZkpProvingKey       []byte                                   `protobuf:"bytes,12,opt,name=zkp_proving_key,json=zkpProvingKey,proto3" json:"zkp_proving_key,omitempty"`
	ZkpVerifyingKey     []byte                                   `protobuf:"bytes,13,opt,name=zkp_verifying_key,json=zkpVerifyingKey,proto3" json:"zkp_verifying_key,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_ece6e991701bb4fc, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSlashEpoch() uint64 {
	if m != nil {
		return m.SlashEpoch
	}
	return 0
}

func (m *Params) GetEpochMaxFault() uint64 {
	if m != nil {
		return m.EpochMaxFault
	}
	return 0
}

func (m *Params) GetMinShardCount() uint64 {
	if m != nil {
		return m.MinShardCount
	}
	return 0
}

func (m *Params) GetMaxShardCount() uint64 {
	if m != nil {
		return m.MaxShardCount
	}
	return 0
}

func (m *Params) GetMaxShardSize() uint64 {
	if m != nil {
		return m.MaxShardSize
	}
	return 0
}

func (m *Params) GetChallengePeriod() time.Duration {
	if m != nil {
		return m.ChallengePeriod
	}
	return 0
}

func (m *Params) GetProofPeriod() time.Duration {
	if m != nil {
		return m.ProofPeriod
	}
	return 0
}

func (m *Params) GetChallengeCollateral() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.ChallengeCollateral
	}
	return nil
}

func (m *Params) GetZkpProvingKey() []byte {
	if m != nil {
		return m.ZkpProvingKey
	}
	return nil
}

func (m *Params) GetZkpVerifyingKey() []byte {
	if m != nil {
		return m.ZkpVerifyingKey
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "lyfebloc.da.Params")
}

func init() { proto.RegisterFile("lyfebloc/da/params.proto", fileDescriptor_ece6e991701bb4fc) }

var fileDescriptor_ece6e991701bb4fc = []byte{
	// 610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0x8e, 0x69, 0x09, 0xad, 0x93, 0xb4, 0xd4, 0x74, 0x30, 0x45, 0x38, 0x11, 0x20, 0x14, 0x55,
	0xc2, 0x47, 0x61, 0x63, 0x4c, 0x4b, 0x84, 0x28, 0xa0, 0x2a, 0x45, 0x0c, 0x2c, 0xd6, 0xe5, 0x7c,
	0xb6, 0x4f, 0xb1, 0xfd, 0xac, 0xbb, 0x4b, 0x88, 0x33, 0xf0, 0x03, 0x98, 0x18, 0x19, 0x99, 0x99,
	0xf8, 0x05, 0xcc, 0x1d, 0x3b, 0x22, 0x86, 0x16, 0xb5, 0x03, 0xfc, 0x0c, 0x74, 0x67, 0x3b, 0x4d,
	0xb7, 0xb2, 0x24, 0xe7, 0xef, 0x7d, 0xdf, 0x77, 0xef, 0xbd, 0x7b, 0xcf, 0xb4, 0xe3, 0x3c, 0xa0,
	0xc3, 0x18, 0x08, 0xf2, 0x31, 0xca, 0x30, 0xc7, 0x89, 0x70, 0x33, 0x0e, 0x12, 0xac, 0x46, 0x15,
	0x71, 0x7d, 0xbc, 0xb5, 0x81, 0x13, 0x96, 0x02, 0xd2, 0xbf, 0x45, 0x7c, 0x6b, 0x33, 0x84, 0x10,
	0xf4, 0x11, 0xa9, 0x53, 0x89, 0x3a, 0x04, 0x44, 0x02, 0x02, 0x0d, 0xb1, 0xa0, 0x68, 0xb2, 0x33,
	0xa4, 0x12, 0xef, 0x20, 0x02, 0x2c, 0xad, 0xe2, 0x21, 0x40, 0x18, 0x53, 0xa4, 0xbf, 0x86, 0xe3,
	0x00, 0xf9, 0x63, 0x8e, 0x25, 0x83, 0x32, 0x7e, 0xef, 0x47, 0xdd, 0xac, 0x1f, 0xe8, 0x34, 0xac,
	0x97, 0xe6, 0xda, 0x04, 0x24, 0xf5, 0x64, 0xc4, 0xa9, 0x88, 0x20, 0xf6, 0x6d, 0xa3, 0x63, 0x74,
	0x57, 0x7b, 0xf7, 0x8f, 0x4e, 0xda, 0xb5, 0x5f, 0x27, 0xed, 0x3b, 0xc5, 0x55, 0xc2, 0x1f, 0xb9,
	0x0c, 0x50, 0x82, 0x65, 0xe4, 0xbe, 0xa2, 0x21, 0x26, 0xf9, 0x1e, 0x25, 0x83, 0x96, 0x92, 0xbe,
	0xad, 0x94, 0x56, 0xdb, 0x6c, 0x88, 0x18, 0x8b, 0xc8, 0xa3, 0x19, 0x90, 0xc8, 0xbe, 0xd6, 0x31,
	0xba, 0xcb, 0x03, 0x53, 0x43, 0xcf, 0x15, 0x62, 0x3d, 0x34, 0xd7, 0x75, 0xc8, 0x4b, 0xf0, 0xd4,
	0x0b, 0xf0, 0x38, 0x96, 0xf6, 0x92, 0x26, 0xb5, 0x34, 0xfc, 0x1a, 0x4f, 0xfb, 0x0a, 0x54, 0x49,
	0x15, 0x46, 0x01, 0xc7, 0x44, 0xe5, 0x6d, 0x2f, 0xff, 0x47, 0x52, 0x5a, 0xda, 0x2f, 0x95, 0xd6,
	0xc0, 0xb4, 0x38, 0xcd, 0x62, 0x46, 0x74, 0x03, 0xbc, 0x00, 0x13, 0x09, 0xdc, 0xbe, 0x7e, 0x75,
	0xbf, 0x8d, 0x05, 0x79, 0x5f, 0xab, 0x55, 0x1d, 0x09, 0x4b, 0x3d, 0x11, 0x61, 0xee, 0x7b, 0x04,
	0xc6, 0xa9, 0xb4, 0xeb, 0x45, 0x1d, 0x09, 0x4b, 0x0f, 0x15, 0xba, 0xab, 0x40, 0xcd, 0xc3, 0xd3,
	0x4b, 0xbc, 0x1b, 0x25, 0x0f, 0x4f, 0x17, 0x78, 0x0f, 0xcc, 0xb5, 0x0b, 0x9e, 0x60, 0x33, 0x6a,
	0xaf, 0x68, 0x5a, 0xb3, 0xa2, 0x1d, 0xb2, 0x19, 0xb5, 0xde, 0x98, 0x37, 0x49, 0x84, 0xe3, 0x98,
	0xa6, 0x21, 0xf5, 0x32, 0xca, 0x19, 0xf8, 0xf6, 0x6a, 0xc7, 0xe8, 0x36, 0x9e, 0xdc, 0x76, 0x8b,
	0x07, 0x77, 0xab, 0x07, 0x77, 0xf7, 0xca, 0x07, 0xef, 0xad, 0xa8, 0x12, 0xbf, 0x9c, 0xb6, 0x8d,
	0xc1, 0xfa, 0x5c, 0x7c, 0xa0, 0xb5, 0x56, 0xdf, 0x6c, 0x66, 0x1c, 0x20, 0xa8, 0xbc, 0xcc, 0xab,
	0x7b, 0x35, 0xb4, 0xb0, 0xf4, 0xf9, 0x68, 0x6e, 0x5e, 0xe4, 0x45, 0x20, 0x8e, 0xb1, 0xa4, 0x1c,
	0xc7, 0x76, 0xa3, 0xb3, 0xa4, 0xfd, 0x8a, 0xe6, 0xba, 0x6a, 0x58, 0xdd, 0x72, 0x58, 0xdd, 0x5d,
	0x60, 0x69, 0xef, 0xb1, 0xf2, 0xfb, 0x76, 0xda, 0xee, 0x86, 0x4c, 0x46, 0xe3, 0xa1, 0x4b, 0x20,
	0x41, 0xe5, 0x64, 0x17, 0x7f, 0x8f, 0x84, 0x3f, 0x42, 0x32, 0xcf, 0xa8, 0xd0, 0x02, 0x31, 0xb8,
	0x35, 0xbf, 0x68, 0x77, 0x7e, 0x8f, 0xea, 0xf2, 0x6c, 0x94, 0x79, 0x19, 0x87, 0x09, 0x4b, 0x43,
	0x6f, 0x44, 0x73, 0xbb, 0xd9, 0x31, 0xba, 0xcd, 0x41, 0x6b, 0x36, 0xca, 0x0e, 0x0a, 0x74, 0x9f,
	0xe6, 0xd6, 0xb6, 0xb9, 0xa1, 0x78, 0x13, 0xca, 0x59, 0x90, 0x57, 0xcc, 0x96, 0x66, 0x2a, 0x83,
	0x77, 0x15, 0xbe, 0x4f, 0xf3, 0x67, 0x77, 0xff, 0x7e, 0x6d, 0x1b, 0x9f, 0xfe, 0x7c, 0xdf, 0xde,
	0x9c, 0xaf, 0xee, 0x54, 0x2d, 0x6f, 0xb1, 0x35, 0xbd, 0x17, 0x47, 0x67, 0x8e, 0x71, 0x7c, 0xe6,
	0x18, 0xbf, 0xcf, 0x1c, 0xe3, 0xf3, 0xb9, 0x53, 0x3b, 0x3e, 0x77, 0x6a, 0x3f, 0xcf, 0x9d, 0xda,
	0x7b, 0x77, 0xa1, 0x96, 0x4a, 0x9a, 0x52, 0xf9, 0x01, 0xf8, 0x08, 0x5d, 0xb6, 0xd2, 0x75, 0x0d,
	0xeb, 0xba, 0xcd, 0x4f, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0x92, 0x0f, 0x53, 0xc8, 0x23, 0x04,
	0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.VoteThreshold.Equal(that1.VoteThreshold) {
		return false
	}
	if this.SlashEpoch != that1.SlashEpoch {
		return false
	}
	if this.EpochMaxFault != that1.EpochMaxFault {
		return false
	}
	if !this.SlashFraction.Equal(that1.SlashFraction) {
		return false
	}
	if !this.ReplicationFactor.Equal(that1.ReplicationFactor) {
		return false
	}
	if this.MinShardCount != that1.MinShardCount {
		return false
	}
	if this.MaxShardCount != that1.MaxShardCount {
		return false
	}
	if this.MaxShardSize != that1.MaxShardSize {
		return false
	}
	if this.ChallengePeriod != that1.ChallengePeriod {
		return false
	}
	if this.ProofPeriod != that1.ProofPeriod {
		return false
	}
	if len(this.ChallengeCollateral) != len(that1.ChallengeCollateral) {
		return false
	}
	for i := range this.ChallengeCollateral {
		if !this.ChallengeCollateral[i].Equal(&that1.ChallengeCollateral[i]) {
			return false
		}
	}
	if !bytes.Equal(this.ZkpProvingKey, that1.ZkpProvingKey) {
		return false
	}
	if !bytes.Equal(this.ZkpVerifyingKey, that1.ZkpVerifyingKey) {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ZkpVerifyingKey) > 0 {
		i -= len(m.ZkpVerifyingKey)
		copy(dAtA[i:], m.ZkpVerifyingKey)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ZkpVerifyingKey)))
		i--
		dAtA[i] = 0x6a
	}
	if len(m.ZkpProvingKey) > 0 {
		i -= len(m.ZkpProvingKey)
		copy(dAtA[i:], m.ZkpProvingKey)
		i = encodeVarintParams(dAtA, i, uint64(len(m.ZkpProvingKey)))
		i--
		dAtA[i] = 0x62
	}
	if len(m.ChallengeCollateral) > 0 {
		for iNdEx := len(m.ChallengeCollateral) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ChallengeCollateral[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.ProofPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ProofPeriod):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x52
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.ChallengePeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ChallengePeriod):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x4a
	if m.MaxShardSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxShardSize))
		i--
		dAtA[i] = 0x40
	}
	if m.MaxShardCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxShardCount))
		i--
		dAtA[i] = 0x38
	}
	if m.MinShardCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinShardCount))
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.ReplicationFactor.Size()
		i -= size
		if _, err := m.ReplicationFactor.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.SlashFraction.Size()
		i -= size
		if _, err := m.SlashFraction.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.EpochMaxFault != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.EpochMaxFault))
		i--
		dAtA[i] = 0x18
	}
	if m.SlashEpoch != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SlashEpoch))
		i--
		dAtA[i] = 0x10
	}
	{
		size := m.VoteThreshold.Size()
		i -= size
		if _, err := m.VoteThreshold.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.VoteThreshold.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.SlashEpoch != 0 {
		n += 1 + sovParams(uint64(m.SlashEpoch))
	}
	if m.EpochMaxFault != 0 {
		n += 1 + sovParams(uint64(m.EpochMaxFault))
	}
	l = m.SlashFraction.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.ReplicationFactor.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.MinShardCount != 0 {
		n += 1 + sovParams(uint64(m.MinShardCount))
	}
	if m.MaxShardCount != 0 {
		n += 1 + sovParams(uint64(m.MaxShardCount))
	}
	if m.MaxShardSize != 0 {
		n += 1 + sovParams(uint64(m.MaxShardSize))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ChallengePeriod)
	n += 1 + l + sovParams(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.ProofPeriod)
	n += 1 + l + sovParams(uint64(l))
	if len(m.ChallengeCollateral) > 0 {
		for _, e := range m.ChallengeCollateral {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = len(m.ZkpProvingKey)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.ZkpVerifyingKey)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VoteThreshold", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.VoteThreshold.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashEpoch", wireType)
			}
			m.SlashEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlashEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochMaxFault", wireType)
			}
			m.EpochMaxFault = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochMaxFault |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashFraction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SlashFraction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplicationFactor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ReplicationFactor.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinShardCount", wireType)
			}
			m.MinShardCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinShardCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxShardCount", wireType)
			}
			m.MaxShardCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxShardCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxShardSize", wireType)
			}
			m.MaxShardSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxShardSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengePeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.ChallengePeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProofPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.ProofPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChallengeCollateral", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChallengeCollateral = append(m.ChallengeCollateral, types.Coin{})
			if err := m.ChallengeCollateral[len(m.ChallengeCollateral)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZkpProvingKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZkpProvingKey = append(m.ZkpProvingKey[:0], dAtA[iNdEx:postIndex]...)
			if m.ZkpProvingKey == nil {
				m.ZkpProvingKey = []byte{}
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZkpVerifyingKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZkpVerifyingKey = append(m.ZkpVerifyingKey[:0], dAtA[iNdEx:postIndex]...)
			if m.ZkpVerifyingKey == nil {
				m.ZkpVerifyingKey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
