name: "Consensus Warn"

permissions: read-all

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    permissions:
      pull-requests: write # For reading the PR and posting comment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: orijtech/consensuswarn@main
        with:
          roots: "github.com/lyfeblocnetwork/lyfebloc/app.Lyfebloc.FinalizeBlock,github.com/lyfeblocnetwork/lyfebloc/app.Lyfebloc.BeginBlocker,github.com/lyfeblocnetwork/lyfebloc/app.Lyfebloc.EndBlocker"
